### ISSUE TITLE
0.15?

### ISSUE THREAD

**Issue by abordoli** [jocker-il/MoreLogisticSlots#2]
Any plans to port this up to 0.15?
Regards,
~B

**Comment by jocker-il** [comment]
It will require re-thinking the whole tech costs since the science packs have changed in 0.15. I actualy want it too, but it's much work for one person...

**Comment by abordoli** [comment]
Thxs!

**Comment by jocker-il** [comment]
# updated to Factorio 0.15.x - Issue #3 #4 #5 

 you'r welcome to test and comment / make a changes and pull requests

version are **[here](https://github.com/jocker-il/MoreLogisticsSlots/releases)**
